"""add_chat_session_table

Revision ID: 3277eda376fd
Revises: ca184acdaf56
Create Date: 2026-08-04 16:38:19.157711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision: str = '3277eda376fd'
down_revision: Union[str, Sequence[str], None] = 'ca184acdaf56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None




def upgrade() -> None:
    # 创建 chatsession 表
    op.create_table('chatsession',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=100), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatsession_user_id'), 'chatsession', ['user_id'], unique=False)

    # 添加 session_id 列，先允许为空
    op.add_column('message', sa.Column('session_id', sa.Integer(), nullable=True))
    
    # 为有消息的用户创建默认会话并关联
    connection = op.get_bind()
    # 获取所有有消息的用户
    users = connection.execute(sa.text("SELECT DISTINCT user_id FROM message"))
    for user in users:
        user_id = user[0]
        # 创建默认会话
        result = connection.execute(
            sa.text("""
                INSERT INTO chatsession (user_id, title, is_active, created_at, updated_at)
                VALUES (:user_id, :title, :is_active, :created_at, :updated_at)
                RETURNING id
            """),
            {
                "user_id": user_id,
                "title": "默认会话",
                "is_active": True,
                "created_at": datetime.now(),
                "updated_at": datetime.now()
            }
        )
        default_session_id = result.fetchone()[0]
        # 更新该用户所有消息
        connection.execute(
            sa.text("UPDATE message SET session_id = :session_id WHERE user_id = :user_id"),
            {"session_id": default_session_id, "user_id": user_id}
        )
    
    # 4. 所有行都有 session_id，设置为 NOT NULL
    op.alter_column('message', 'session_id', nullable=False)
    
    # 5. 创建索引和外键
    op.create_index(op.f('ix_message_session_id'), 'message', ['session_id'], unique=False)
    op.create_foreign_key(None, 'message', 'chatsession', ['session_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_index(op.f('ix_message_session_id'), table_name='message')
    op.drop_column('message', 'session_id')
    op.drop_index(op.f('ix_chatsession_user_id'), table_name='chatsession')
    op.drop_table('chatsession')
    # ### end Alembic commands ###
